version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: production
  scrapers:
    build: ./scrapers
    container_name: gre4ka-scrapers
    ports:
      - "8000:8000"
  stats:
    build: ./stats
    container_name: gre4ka-stats
    ports:
      - "8080:8080"
    depends_on:
      - scrapers
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/production
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
  frontend:
    build: ./frontend
    container_name: gre4ka-client
    ports:
      - "80:80"
    depends_on:
      - scrapers
      - stats